import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={GeistSans.variable}>
        <body>
          <div className="bg-grid-white/[0.1] relative min-h-screen w-full bg-[#0A0A0A]">
            {/* Radial gradient overlay */}
            <div className="pointer-events-none absolute inset-0 bg-black [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
            {/* Content container with navbar and footer */}
            <div className="relative z-10 flex min-h-screen flex-col gap-12">
              <Navbar />
              <main className="mt-12 flex-1">{children}</main>
              <Footer />
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
